# Generated by Django 4.2.3 on 2023-07-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="price",
            new_name="color",
        ),
    ]
